-- AlterEnum
ALTER TYPE "UsersStatus" ADD VALUE 'BANNED';

-- AlterTable
ALTER TABLE "Ban" ALTER COLUMN "ban_start" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "ban_end" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Users" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
